version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - STORAGE_PATH=/app/data
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    volumes:
      - bot-data:/app/data
      - ./sessions:/app/sessions
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    cap_add:
      - SYS_ADMIN
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    security_opt:
      - seccomp=unconfined
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "node", "./dist/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  bot-data: 